### ISSUE TITLE
10.10.10.10 is not a valid bluetooth address

### ISSUE THREAD

**Issue by jturingan25** [leesiongchan/react-native-esc-pos#11]
Hi, I'm using bluetooth config. What is the need in the first param of the connect? is it mac address of the device?

**Comment by leesiongchan** [comment]
Yes, the mac address.

**Comment by jturingan25** [comment]
got it. thanks! it's working now. By the way in the print image is it base64?

**Comment by leesiongchan** [comment]
I am truly sorry for the improper documentation, I am going to improve it when I have time, and no, the `printImage` function is currently supported only for the `uri` format (eg. https://photos.laineygossip.com/articles/brad-pitt-allied-10nov16-03.jpg).
