### ISSUE TITLE
Turkish character problem

### ISSUE THREAD

**Issue by sefatamak** [leesiongchan/react-native-esc-pos#18]
I have problem in Turkish characters. It writes '?' instead of character. Turkish characters are  ğ, Ğ, ç, Ç, ş, Ş, ü, Ü, ö, Ö, ı, İ .How can I solve it ?

**Comment by sefatamak** [comment]
@leesiongchan

**Comment by leesiongchan** [comment]
Will need to expose the charset API in order to fix this, I will see if I have extra time over the weekend.

**Comment by sefatamak** [comment]
Thank you! I'll wait for this

**Comment by leesiongchan** [comment]
@sefatamak sorry haven't had time to look into it yet... I will look into this once I have time, I will need to provide this feature nonetheless.

**Comment by sefatamak** [comment]
Ok I will wait you @leesiongchan

**Comment by slavikdenis** [comment]
This would be much neeeded. Im trying to implement Czech characters (https://en.wikipedia.org/wiki/Windows-1250)

**Comment by leesiongchan** [comment]
Same as #57
