### ISSUE TITLE
printBarcode

### ISSUE THREAD

**Issue by ydancziger** [leesiongchan/react-native-esc-pos#24]
Hi

I see there is an available function `printBarcode()` is this ready to use? if yes, how?
And can you explain a little more how I get an image with `printImage()`

Thank you so much

**Comment by leesiongchan** [comment]
> I see there is an available function printBarcode() is this ready to use? if yes, how?

Sorry `printBarcode()` is [not working](https://github.com/leesiongchan/react-native-esc-pos#todo) yet, hope you could lend a hand on making it work.

>  And can you explain a little more how I get an image with `printImage()`

The only parameter you need to make it work is `filePath`, for example if you use [Expo Image Picker](https://docs.expo.io/versions/latest/sdk/imagepicker/) you will get a `uri`, put in the `uri` you should be able to print the image

**Comment by piarachmayati** [comment]
> > I see there is an available function printBarcode() is this ready to use? if yes, how?
> 
> Sorry `printBarcode()` is [not working](https://github.com/leesiongchan/react-native-esc-pos#todo) yet, since we are using a lib behind the scene, there should only be a very minimal work required for it to work, hope you could lend a hand on making it live 
> 
> > And can you explain a little more how I get an image with `printImage()`
> 
> The only parameter you need to make it work is `filePath`, for example if you use [Expo Image Picker](https://docs.expo.io/versions/latest/sdk/imagepicker/) you will get a `uri`, put in the `uri` you should be able to print the image

for print image, can i get the image file from server?
