### ISSUE TITLE
I want to print text

### ISSUE THREAD

**Issue by JuanCamilo0809** [leesiongchan/react-native-esc-pos#26]
Hi, 

I have 2 problems, when I try to discover printer i have the first error.

it´s with this line of code:
EscPos.scanDevices();

![IMG_63E8CE9F9E11-1](https://user-images.githubusercontent.com/45131355/70581447-3ad72500-1b85-11ea-84c7-1af18d9054d2.jpeg)

the second error is when i try to connect the printer.

connet is not a function.

Maybe do you have any example please?
Thanks a lot

**Comment by leesiongchan** [comment]
Sorry, iOS is not currently supported, PR is welcome!

**Comment by leesiongchan** [comment]
Related to #6
