### ISSUE TITLE
Unable to run in IOS

### ISSUE THREAD

**Issue by co2nut** [leesiongchan/react-native-esc-pos#27]
getting error 
TypeError: _reactNative.NativeModules.EscPos.connectNetworkPrinter is not a function

Kindly assist

Thanks

**Comment by leesiongchan** [comment]
Sorry @co2nut iOS is not currently supported, PR is welcome!

**Comment by leesiongchan** [comment]
Related to #6

**Comment by yom-elect** [comment]
Please i can seem to get the list of bluetooth devices, and their mac address, the mac address is in a call back function and i am having difficulties getting it outside the addListener

**Comment by leesiongchan** [comment]
@yom-elect Can you show us a snippet of your code?
