### ISSUE TITLE
How many main tag design?

### ISSUE THREAD

**Issue by thanhchuongitc** [leesiongchan/react-native-esc-pos#31]
I see in example design: 
{<>} is mean tab
{H1} to {H5} is the same <H 1> to <H 5> in html
other tag is where ?

**Comment by KeeganFargher** [comment]
I read through the source code, here's a list of the commands:

```
            boolean bold = line.contains("{B}");
            boolean underline = line.contains("{U}");
            boolean h1 = line.contains("{H1}");
            boolean h2 = line.contains("{H2}");
            boolean h3 = line.contains("{H3}");
            boolean lsm = line.contains("{LS:M}");
            boolean lsl = line.contains("{LS:L}");
            boolean ct = line.contains("{C}");
            boolean rt = line.contains("{R}");
```

you can have a look [here](https://github.com/leesiongchan/react-native-esc-pos/blob/master/android/src/main/java/leesiongchan/reactnativeescpos/PrinterService.java#L190)

**Comment by KannarFr** [comment]
Hi, thanks for sharing this, but what means lsm, lsl, ct and rt?

**Comment by KeeganFargher** [comment]
Try look at the string inside the .contains() method, not the boolean variable, such as {B}, {U}, etc.

The only unclear ones are these::

{LS:M} - means line space 24
{LS:L}  - means line space 30
{C}      - means center text
{R}      - means right align text

**Comment by KannarFr** [comment]
Ahah sure, when I meant what is lsm, lsl, ct and rt, I meant what mean {LS:M}, {LS:L}, ...

And you just answered, thanks.

**Comment by leesiongchan** [comment]
I have updated the [README](https://github.com/leesiongchan/react-native-esc-pos/issues/24#issuecomment-558902168).
