### ISSUE TITLE
Designing

### ISSUE THREAD

**Issue by Hetal2425** [leesiongchan/react-native-esc-pos#35]
Could anyone please provide the different tag which I can use for design my print. I am facing issue in designing the print as I don't know which tag can be used. So it would be great if someone can help me with my issue. For eg. which tag I can use for breaking the line and putting content into the new line and which tag I can use for adding an image in print?

Thanks

**Comment by KeeganFargher** [comment]
I answered here if you are interested #31

**Comment by leesiongchan** [comment]
I have updated in the [README](https://github.com/leesiongchan/react-native-esc-pos/issues/24#issuecomment-558902168).
