### ISSUE TITLE
printQRCode issue

### ISSUE THREAD

**Issue by KannarFr** [leesiongchan/react-native-esc-pos#38]
```
[Sun Apr 26 2020 07:49:03.847]  LOG      [TypeError: _reactNativeEscPos.EscPos.printQRCOde is not a function. (In '_reactNativeEscPos.EscPos.printQRCOde("Proxima b is the answer!")', '_reactNativeEscPos.EscPos.printQRCOde' is undefined)]
```

Got this error on printQRCode, haven't the problem with printSample, just `{QR[xxx]}` is printed as-is. No QR code displayed. 

@leesiongchan do you have an idea? I checked the code and the method is correctly defined.

**Comment by leesiongchan** [comment]
Hi I see a typo, "printQRCOde" it should be "printQRCode"

**Comment by leesiongchan** [comment]
Aha! Its my typo in README, I have fixed it!
