### ISSUE TITLE
It freezes on the Escpos connect function

### ISSUE THREAD

**Issue by sefatamak** [leesiongchan/react-native-esc-pos#8]
await EscPos.connect("10.10.10.10", 9100);
When I close the printer and trying to connect to printer, app freezes. I want that it gives error when I close the printer. How can I solve it ?

**Comment by leesiongchan** [comment]
Thank you for reporting, I think the library is still unable to handle error correctly, let me relook into the implementation and fix them accordingly in the next few days.

**Comment by sefatamak** [comment]
Thank you for answer. I'll wait for this

**Comment by sefatamak** [comment]
I still wait for this. When can you do it ?

**Comment by leesiongchan** [comment]
How about this coming weekend. I will fix it.

**Comment by leesiongchan** [comment]
@sefatamak I have just pushed a new version, you should now be able to catch it using `.catch` or `try catch block`, I do not have a printer with me now I hope I didn't break anything, please do let me know if it is working. Thanks!

**Comment by sefatamak** [comment]
@leesiongchan Thank you! I will try it

**Comment by bradjones1** [comment]
@leesiongchan Looks like there is a regression regarding https://github.com/leesiongchan/react-native-esc-pos/commit/a58c650d3fed86d94fe96c94696239fa3af5c6c8:

```
> Task :@leesiongchan_react-native-esc-pos:compileDebugJavaWithJavac FAILED
/home/bradj/www/fishadmin/node_modules/@leesiongchan/react-native-esc-pos/android/src/main/java/leesiongchan/reactnativeescpos/EscPosModule.java:211: error: exception IOException is never thrown in body of corresponding try statement
        } catch (IOException e) {
          ^
/home/bradj/www/fishadmin/node_modules/@leesiongchan/react-native-esc-pos/android/src/main/java/leesiongchan/reactnativeescpos/EscPosModule.java:225: error: exception IOException is never thrown in body of corresponding try statement
        } catch (IOException e) {
          ^
Note: /home/bradj/www/fishadmin/node_modules/@leesiongchan/react-native-esc-pos/android/src/main/java/leesiongchan/reactnativeescpos/EscPosModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.
```

I'm not a java developer myself but after a bit of investigating this seems actually to be related to some missing `throws` declarations on the constructors for `PrinterService`. See PR below for an update that at least gets this building.

**Comment by sefatamakkk** [comment]
It freezes again. It doesn't work. Can you help me ?

**Comment by sefatamak** [comment]
I put try catch block but it doesn't work. It freezes. You can try it without printer. You can put connect code inside try catch block without printer and app will freezes. I need this when user's printer broke or close.

**Comment by sefatamak** [comment]
Do you look this issue? I need this quickly. Please help me

**Comment by leesiongchan** [comment]
@sefatamak I will try to look into the issue over the weekend.

**Comment by sefatamak** [comment]
Ok @leesiongchan please answer quickly. My customers wait me for this.

**Comment by bradjones1** [comment]
@sefatamak I'm just going to chime in here and kindly remind you this is an open-source project for which there is no payment in play. To pressure others to work quickly because of a business consideration on your part is unfair. If it is that important, a typical model in this case would be to offer to sponsor development.

**Comment by sefatamak** [comment]
No its wrong, my app is free. I mean that my users wait me for this. You misunderstand. I just trust this project and team. That's it.

**Comment by sefatamak** [comment]
@leesiongchan you can close this issue. I tried again and it works. I think problem is my bundle. I changed version but it didn't change at the begining. Now its ok. App doesn't freezes. Thank you for help 😊

**Comment by leesiongchan** [comment]
@sefatamak Glad to hear that!

**Comment by KannarFr** [comment]
@leesiongchan It still freezing app on connect, the render is applied only after connect success or fail. If I call a print with first instruction "show loader" and then connect, it's waiting for connect to success or fail to really render.
